version: '3.3'

services: 
    wordpress:
        build: ./wordpress
        restart: always
        ports: 
            - 8082:80
        environment: 
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: exampleuser
            WORDPRESS_DB_PASSWORD: examplepass
            WORDPRESS_DB_NAME: exampledb
        volumes: 
            - ./wordpress/themes/:/var/www/html/wp-content/themes
            - ./wordpress/plugins/:/var/www/html/wp-content/plugins
        depends_on: 
            - db

    db:
      build: ./db
      restart: always
      ports: 
        - 3306:3306
      volumes:
        - ./db/data:/var/lib/mysql

networks: 
    back: